use termo8;
DECLARE 
    @DESCRIPCION VARCHAR(40), 
    @CUENTA VARCHAR(15),
	@FIRST VARCHAR(70),
	@SQL VARCHAR(70),
	@QUERY VARCHAR(250);

DECLARE LOOP_CALC_DEBE CURSOR FOR 

SELECT DESCRIPCION, CUENTA FROM REF_MA_DEBE;

OPEN LOOP_CALC_DEBE;

FETCH FROM LOOP_CALC_DEBE INTO @DESCRIPCION, @CUENTA;

WHILE @@FETCH_STATUS = 0

BEGIN
--SELECT @DESCRIPCION;
SET @SQL = 'SUM (P.'+@DESCRIPCION+')';

SET @QUERY = 'SELECT ('''+@DESCRIPCION+''')AS NOM_CUENTA,
('''+@CUENTA+''') AS CUENTA, 
('+@SQL+') AS VALORES FROM PIVOT_REP_CUENTAS P';

exec(@QUERY);
/*SELECT @QUERY;*/


FETCH NEXT FROM LOOP_CALC_DEBE INTO 
@DESCRIPCION, @CUENTA;

END;

CLOSE LOOP_CALC_DEBE;
 
DEALLOCATE LOOP_CALC_DEBE;

/*
SELECT (@DESCRIPCION) AS NOM_CUENTA,
(@CUENTA) AS CUENTA, 
(SUM(P.PT_CM_GAB)) AS VALORES
FROM PIVOT_REP_CUENTAS P
select * from REF_MA_DEBE
select * from PIVOT_REP_CUENTAS
UPDATE REF_MA_DEBE SET DESCRIPCION = 'AAAA' WHERE ID = '2'
*/


