USE TERMO8;

DECLARE 
    @CUENTA VARCHAR(15),
	@NOM VARCHAR(25);

DECLARE LOOP_CALC_HABER CURSOR FOR 

  SELECT CUENTA, NOM_CUENTA FROM REF_MA_HABER GROUP BY NOM_CUENTA, CUENTA;

OPEN LOOP_CALC_HABER;

FETCH FROM LOOP_CALC_HABER INTO @CUENTA, @NOM;

WHILE @@FETCH_STATUS = 0

BEGIN

  SELECT (@NOM) AS NOM_CUENTA,
  (@CUENTA) AS [CUENTA], (select SUM(p.riesgo) from PIVOT_REP_DISTRIB p inner join REF_MA_HABER h on p.INV_MAT_GL_ACCT_ID = h.ID 
  where h.NOM_CUENTA = @NOM)as VALORES ;


FETCH NEXT FROM LOOP_CALC_HABER INTO @CUENTA, @NOM;
END

CLOSE LOOP_CALC_HABER;
 
DEALLOCATE LOOP_CALC_HABER;