USE TERMO8;
Drop table PIVOT_CUENTA_CONTABLE;
CREATE TABLE PIVOT_CUENTA_CONTABLE (
ID INT IDENTITY(1,1) PRIMARY KEY,
CUENTA varchar(15),
COMPANIA varchar(20),
NOM_CUENTA varchar(50),
DEBE decimal(16,6),
HABER decimal(16,6),
CORTE varchar(150)
)


TRUNCATE TABLE PIVOT_CUENTA_CONTABLE;

INSERT INTO PIVOT_CUENTA_CONTABLE
  SELECT H.CUENTA, (NULL) AS COMPANIA, H.NOM_CUENTA, (NULL) AS DEBE, (H.VALORES) AS HABER, (NULL) AS CORTE
  FROM PIVOT_REP_HABER H
  union
  SELECT D.CUENTA, (NULL) AS COMPANIA, D.NOM_CUENTA, (D.VALORES) AS DEBE, (NULL) AS HABER, (NULL) AS CORTE
  FROM PIVOT_REP_DEBE D order by cuenta;

  SELECT * FROM PIVOT_CUENTA_CONTABLE;