USE TERMO8;
Drop table REF_MA_BODEGA;
CREATE TABLE REF_MA_BODEGA (
ID int IDENTITY(1,1) PRIMARY KEY,
LOCATION_ID varchar(30) unique,
[DESCRIPTION] varchar(70),
PERCENTAGE decimal(3,2),
CREATION_DATE DATETIME2,
UPDATE_DATE DATETIME2,
ACTIVE bit DEFAULT 1
)

USE TERMO8;
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-AI-CUA', 'LOCALIZACION DE CUARENTENA INSUMOS I ACCESORIOS', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-BOP-CU', 'LOCALIZACION CUARENTENA BOBINA COMPRADA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-CUA-TIN', 'LOCALIZACION DE CUARENTENA TINTA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-GR-PNC', 'LOCALIZACION NO CONFORME GRABADOS', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-PT-PNC', 'LOCALIZACION NO CONFORME PRODUCTO TERMINADO MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-PT-SPR', 'LOCALIZACION SOBREPRODUCCION PRODUCTO TERMINADO MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-ST-PNC', 'LOCALIZACION NO CONFORME SEMI TERMINADO MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-ST-SPR', 'LOCALIZACION SOBREPRODUCCION SEMI TERMINADO MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-PT-CU', 'LOCALIZACION DE CENTRO DE DISTRIBUCION-CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-PT-SPR', 'LOCALIZACION DE CD- SOBREPRODUCCIONES', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PT-CM-PNC', 'LOCALIZACION DE PNC POR CAMBIOS EN RECLAMOS DE CLIENTES', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-GR-RCH', 'LOCALIZACION RECHAZO GRABADOS', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-PN-MCH', 'LOCALIZACION RECHAZO MECHAS MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-PN-RCH', 'LOCALIZACION RECHAZO PRODUCTO TERMINADO MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('BOD-ML-CU', 'LOCALIZACION DE PRODUCTO SEMI TERMINADO CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('BOD-ML-SPR', 'LOCALIZACION DE SOBREPRODUCCION MERLIT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ML-ST-SPR', 'LOCALIZACION DE SOBREPRODCCION SEMI TERMINADO MERLIOT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('MQH-TUB-CUA', 'LOCALIZACION DE POLIDUCTO EN CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('MQT-AI-CUA', 'LOCALIZACION DE INSUMOS EN CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('MQT-MP-CUA', 'LOCALIZACIÓN MP CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('MQT-PNC-PT', 'LOCALIZACION DE PRODUCTO NO CONFORME PARA PT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('MQT-CU-PTA', 'CUARENTENA PLANTA MQH', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-AI-CUA', 'LOCALIZACIÓN DE ACCESORIOS E INCUMOS EN CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-MP-RES', 'LOCALIZACION DE RESINAS EN CUARENTENA PLAN DE LA LAGUAN', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('TRANSITO', 'LOCALIZACION DE TRANSITO RESINAS EN CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-MC-PIG', 'PLAN DE LA LAGUNA-MATERIALES EN CUARENTENA-PIGMENTOS', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-MC-RES', 'PLAN DE LA LAGUNA-MATERIALES EN CUARENTENA-RESINAS', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-MP-CUA', 'LOCALIZACION DE CUARENTENA DE MATERIA PRIMA PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-PT-PNC', 'LOCALIZACION NO CONFORME PRODUCTO TERMINADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-PT-SPR', 'LOCALIZACION SOBREPRODUCCION PRODUCTO TERMINADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-ST-PNC', 'LOCALIZACION NO CONFORME SEMITERMINADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-ST-SPR', 'LOCALIZACION SOBREPRODUCCION SEMI TERMINADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-CU-REV', 'LOCALIZACION DE CUARENTENA NC PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-PT-CU', 'LOCALIZACIÓN DE PRODUCTO TERMINADO PARA CALIDAD', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-PT-SPR', 'LOCALZIACION DE SOBREPRODUCCION PT PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-PN-RCH', 'LOCALIZACION RECHAZADO PRODUCTO TERMINADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('TRANSFERENCIAS', 'LOCALIZACION DE TRANSFERENCIA DE PRODUCTO RECHAZADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-RE-EXCE', 'LOCALIZACION DE REPUESTOS EXCEDENTES', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('BOD-PL-CU', 'LOCALIZACION DE CUARENTENA PL SEMI TERMINADO', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('BOD-PL-SPR', 'LOCALZIACION DE SOBREPRODUCCION PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-ST-PSR', 'LOCALIZACION DE SOBREPRODUCCION DE SEMI TERMINADO PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('AL-OP-CUA', 'ALMACENA OPICO CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('DCA-EF-CUA', 'DCA MATERIAL EF CUARENTENA TEMPORAL PL', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ELI-EF-CUA', 'ELICA MATERIAL EF CUARENTENA TEMPORAL CARR.LA LIBERTAD', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('ELI-LL-CUA', 'ELICA LA LIBERTAD BODEGA CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('RA-ML-CUA', 'RANSA MERLIOT CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('RA-SY-CUA', 'RANSA SOYAPANGO CUARENTENA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('TIK-PL-CUA', 'GRUPO TIKAL CUARENTENA PLAN DE LA LAGUNA', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('MQT-PT-CUA', 'LOCALIZACIÓN DE CUARENTENA PT', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('REC-EF-CUA', 'RECICLADO MATERIAL EF CUARENTENA TEMPORAL (RENOVA)', 1, SYSDATETIME(), null, 1);
INSERT INTO REF_MA_BODEGA (LOCATION_ID, [DESCRIPTION], PERCENTAGE, CREATION_DATE, UPDATE_DATE, ACTIVE) VALUES ('PL-MP-CUA', 'LOCALIZACION DE CUARENTENA PARA PELETIZADOS', 1, SYSDATETIME(), null, 1);

select * FROM REF_MA_BODEGA;



select * FROM REF_MA_BODEGA;
update REF_MA_BODEGA set active = 0 where ID = 5;