
create PROCEDURE SP_CALC_HABER
AS
BEGIN

TRUNCATE TABLE PIVOT_REP_HABER;
DECLARE 
    @CUENTA VARCHAR(15),
	--@Q VARCHAR(MAX),
	@NOM VARCHAR(25);

DECLARE LOOP_CALC_HABER CURSOR FOR 

  SELECT CUENTA, NOM_CUENTA FROM REF_MA_HABER GROUP BY CUENTA, NOM_CUENTA;
  --SELECT * FROM REF_MA_HABER;
OPEN LOOP_CALC_HABER;

FETCH FROM LOOP_CALC_HABER INTO @CUENTA, @NOM;

WHILE @@FETCH_STATUS = 0

BEGIN

INSERT INTO PIVOT_REP_HABER
  SELECT (@NOM) AS NOM_CUENTA,
  (@CUENTA) AS [CUENTA], (select SUM(p.riesgo) from PIVOT_REP_CUENTAS p inner join REF_MA_HABER h on p.INV_MAT_GL_ACCT_ID = h.ID 
  where h.NOM_CUENTA = @NOM)as VALORES ;

 /* SET @Q = 'SELECT ('+@NOM+') AS NOM_CUENTA,
  ('+@CUENTA+') AS [CUENTA], (select SUM(p.riesgo) from PIVOT_REP_CUENTAS p inner join REF_MA_HABER h on p.INV_MAT_GL_ACCT_ID = h.ID 
  where h.NOM_CUENTA = '+@NOM+')as VALORES;';

  SELECT @Q;*/

FETCH NEXT FROM LOOP_CALC_HABER INTO @CUENTA, @NOM;
END

CLOSE LOOP_CALC_HABER;
 
DEALLOCATE LOOP_CALC_HABER;

 END;