CREATE PROCEDURE SP_CALC_RIESGO
AS
BEGIN

TRUNCATE TABLE PIVOT_REP_DISTRIB;
INSERT INTO PIVOT_REP_DISTRIB
SELECT P.INV_MAT_GL_ACCT_ID, P.POLITICA, P.PART_ID, P.COMPANIA, P.DISTRIBUCION, P.LOCATION_ID, P.EXCEPCIONES_MP, P.TOTAL,

(
CASE
WHEN (P.LOCATION_ID = (SELECT W.LOCATION_ID FROM REF_MA_BODEGA W WHERE W.LOCATION_ID = P.LOCATION_ID)) THEN (P.TOTAL* ((SELECT PERCENTAGE FROM REF_MA_BODEGA WHERE LOCATION_ID = P.LOCATION_ID and active = 1)))
else(
	CASE
	WHEN (P.EXCEPCIONES_MP LIKE '__-SUN') THEN (
	
			CASE 
				WHEN (P.DIFERENCIA >= 0 AND P.DIFERENCIA <= 30) THEN (P.TOTAL * (SELECT D30 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 31 AND P.DIFERENCIA <= 60) THEN (P.TOTAL * (SELECT D60 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 61 AND P.DIFERENCIA <= 90) THEN (P.TOTAL * (SELECT D90 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 91 AND P.DIFERENCIA <= 120) THEN (P.TOTAL * (SELECT D120 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 121 AND P.DIFERENCIA <= 150) THEN (P.TOTAL * (SELECT D150 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 151 AND P.DIFERENCIA <= 180) THEN (P.TOTAL * (SELECT D180 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 181 AND P.DIFERENCIA <= 210) THEN (P.TOTAL * (SELECT D210 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 211 AND P.DIFERENCIA <= 240) THEN (P.TOTAL * (SELECT D240 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 241 AND P.DIFERENCIA <= 270) THEN (P.TOTAL * (SELECT D270 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA >= 271 AND P.DIFERENCIA <= 360) THEN (P.TOTAL * (SELECT D360 FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
				WHEN (P.DIFERENCIA > 360) THEN (P.TOTAL * (SELECT D360PLUS FROM REF_EXEP_RIESGO WHERE MP = 'SUN-CHEMICAL' and active = 1))
			end
	
	)
	WHEN (P.EXCEPCIONES_MP = 'TIPIND') THEN (
	
			CASE 
				WHEN (P.DIFERENCIA >= 0 AND P.DIFERENCIA <= 30) THEN (P.TOTAL * (SELECT D30 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 31 AND P.DIFERENCIA <= 60) THEN (P.TOTAL * (SELECT D60 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 61 AND P.DIFERENCIA <= 90) THEN (P.TOTAL * (SELECT D90 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 91 AND P.DIFERENCIA <= 120) THEN (P.TOTAL * (SELECT D120 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 121 AND P.DIFERENCIA <= 150) THEN (P.TOTAL * (SELECT D150 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 151 AND P.DIFERENCIA <= 180) THEN (P.TOTAL * (SELECT D180 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 181 AND P.DIFERENCIA <= 210) THEN (P.TOTAL * (SELECT D210 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 211 AND P.DIFERENCIA <= 240) THEN (P.TOTAL * (SELECT D240 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 241 AND P.DIFERENCIA <= 270) THEN (P.TOTAL * (SELECT D270 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA >= 271 AND P.DIFERENCIA <= 360) THEN (P.TOTAL * (SELECT D360 FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
				WHEN (P.DIFERENCIA > 360) THEN (P.TOTAL * (SELECT D360PLUS FROM REF_EXEP_RIESGO WHERE MP = 'TIPIND' and active = 1))
			end
	
	)

	WHEN (P.EXCEPCIONES_MP = 'CARGIL') THEN (
	
			CASE 
				WHEN (P.DIFERENCIA >= 0 AND P.DIFERENCIA <= 30) THEN (P.TOTAL * (SELECT D30 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 31 AND P.DIFERENCIA <= 60) THEN (P.TOTAL * (SELECT D60 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 61 AND P.DIFERENCIA <= 90) THEN (P.TOTAL * (SELECT D90 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 91 AND P.DIFERENCIA <= 120) THEN (P.TOTAL * (SELECT D120 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 121 AND P.DIFERENCIA <= 150) THEN (P.TOTAL * (SELECT D150 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 151 AND P.DIFERENCIA <= 180) THEN (P.TOTAL * (SELECT D180 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 181 AND P.DIFERENCIA <= 210) THEN (P.TOTAL * (SELECT D210 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 211 AND P.DIFERENCIA <= 240) THEN (P.TOTAL * (SELECT D240 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 241 AND P.DIFERENCIA <= 270) THEN (P.TOTAL * (SELECT D270 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA >= 271 AND P.DIFERENCIA <= 360) THEN (P.TOTAL * (SELECT D360 FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
				WHEN (P.DIFERENCIA > 360) THEN (P.TOTAL * (SELECT D360PLUS FROM REF_EXEP_RIESGO WHERE MP = 'CARGIL' and active = 1))
			end
	
	)

	else(
			CASE 
				WHEN (P.DIFERENCIA >= 0 AND P.DIFERENCIA <= 30) THEN (P.TOTAL * (SELECT D30 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 31 AND P.DIFERENCIA <= 60) THEN (P.TOTAL * (SELECT D60 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 61 AND P.DIFERENCIA <= 90) THEN (P.TOTAL * (SELECT D90 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 91 AND P.DIFERENCIA <= 120) THEN (P.TOTAL * (SELECT D120 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 121 AND P.DIFERENCIA <= 150) THEN (P.TOTAL * (SELECT D150 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 151 AND P.DIFERENCIA <= 180) THEN (P.TOTAL * (SELECT D180 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 181 AND P.DIFERENCIA <= 210) THEN (P.TOTAL * (SELECT D210 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 211 AND P.DIFERENCIA <= 240) THEN (P.TOTAL * (SELECT D240 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 241 AND P.DIFERENCIA <= 270) THEN (P.TOTAL * (SELECT D270 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA >= 271 AND P.DIFERENCIA <= 360) THEN (P.TOTAL * (SELECT D360 FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
				WHEN (P.DIFERENCIA > 360) THEN (P.TOTAL * (SELECT D360PLUS FROM REF_POL_RIESGO POL WHERE ID = P.INV_MAT_GL_ACCT_ID and POL.active = 1))
			end
		)
	END
	)
end
) AS RIESGO

 FROM PIVOT_REP_RIESGO_INVENTARIO P 
 END;