CREATE PROCEDURE SP_CALC_DISTRIB
AS
BEGIN

DECLARE 
    @ID VARCHAR(25), @SUB VARCHAR(25), @START VARCHAR(MAX), @END VARCHAR(50), @Q VARCHAR (MAX);

DECLARE LOOP_CALC_DISTR CURSOR FOR 

   SELECT FAMILIA FROM REF_FAMILIAS;

OPEN LOOP_CALC_DISTR;
SET @START = 'SELECT P.INV_MAT_GL_ACCT_ID, P.COMPANIA, P.DISTRIBUCION, P.RIESGO'
SET @END = ' FROM PIVOT_REP_DISTRIB P';
FETCH FROM LOOP_CALC_DISTR INTO @ID;

WHILE @@FETCH_STATUS = 0

BEGIN
 SET @SUB = @ID;
SET @Q = ',(P.RIESGO * (SELECT PERC FROM REF_MA_DISTR WHERE DISTRIBUCION = P.DISTRIBUCION AND familia = '''+@SUB+''')) AS '+@ID+'';
	SET @START = @START+@Q;
	
FETCH NEXT FROM LOOP_CALC_DISTR INTO @ID;

END

TRUNCATE TABLE PIVOT_REP_CUENTAS;
INSERT INTO PIVOT_REP_CUENTAS

EXEC (@START+@END);

CLOSE LOOP_CALC_DISTR;
 
DEALLOCATE LOOP_CALC_DISTR;


 END;
