
create PROCEDURE SP_CALC_DEBE
AS
BEGIN

TRUNCATE TABLE PIVOT_REP_DEBE;
DECLARE 
    @DESCRIPCION VARCHAR(40), 
    @CUENTA VARCHAR(15),
	@SQL VARCHAR(100),
	@QUERY VARCHAR(250);

DECLARE LOOP_CALC_DEBE CURSOR FOR 

SELECT DESCRIPCION, CUENTA FROM REF_MA_DEBE;

OPEN LOOP_CALC_DEBE;

FETCH FROM LOOP_CALC_DEBE INTO @DESCRIPCION, @CUENTA;

WHILE @@FETCH_STATUS = 0

BEGIN
SET @SQL = 'SUM (P.'+@DESCRIPCION+')';

SET @QUERY = 'SELECT ('''+@DESCRIPCION+''')AS NOM_CUENTA,
('''+@CUENTA+''') AS CUENTA, 
('+@SQL+') AS VALORES FROM PIVOT_REP_CUENTAS P';

INSERT INTO PIVOT_REP_DEBE
exec(@QUERY);
--select @QUERY;

FETCH NEXT FROM LOOP_CALC_DEBE INTO 
@DESCRIPCION, @CUENTA;

END;

CLOSE LOOP_CALC_DEBE;
 
DEALLOCATE LOOP_CALC_DEBE;

 END;